config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { registrations: 'users/registrations', sessions: 'users/sessions',
                            passwords: 'users/passwords' }
  # devise_for :users

  # devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/bienvenida', to: 'home#index'

  resources :users do
    get 'my_comments', on: :member
    get 'my_articles', on: :member
  end

  resources :users, only: [:update]
  get 'perfil', to: 'users#edit'
  delete '/users/:id', to: 'users#destroy', as: :delete_user

  # get '/users/:id', to: 'users#show', as: 'user_profile'

  root to: 'home#index'

  resources :categories
  resources :articles do
    get 'user/:user_id', to: 'articles#from_author', on: :collection
    resources :comments, only: %i[create destroy]
  end

  # resources :articles do
  #   resources :comments, only: [:create, :destroy]
  # end

  # get "articles", to:"articles#index"
  # get "articles/new", to: "articles#new", as: :new_articles
  # get "articles/:id", to: "articles#show"
  # get "articles/:id/edit", to: "articles#edit"
  # patch "/articles/:id", to: "articles#update", as: :article
  # post "articles", to: "articles#create"
  # delete "articles/:id", to: "articles#destroy"
end

app/models/article.rb
class Article < ApplicationRecord
  has_rich_text :content
  belongs_to :user, optional: true
  has_many :category_articles
  has_many :categories, through: :category_articles
  has_many :comments, dependent: :destroy

  attr_accessor :category_elements

  def save_categories
    return category_articles.destroy_all if category_elements.nil? || category_elements.empty?

    category_articles.where.not(category_id: category_elements).destroy_all

    # category_elements
    category_elements.each do |category_id|
      CategoryArticle.find_or_create_by(article: self, category_id: category_id)
    end
  end

  def remove_category_association
    category_article = CategoryArticle.find_by(article_id: id)
    category_article.destroy if category_article
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: %i[edit update show destroy]
  before_action :authenticate_user!, only: %i[new edit update create destroy]
  def index
    @articles = Article.all
  end

  def show; end

  def edit
    unless @article.user == current_user || current_user.admin?
      redirect_to articles_path, alert: 'No tienes permiso para editar este artículo.'
    end
    @categories = Category.all
  end

  def update
    unless @article.user == current_user || current_user.admin?
      redirect_to articles_path, alert: 'No tienes permiso para editar este artículo.'
      return
    end
    @article.update(article_params)
    @article.save_categories
    redirect_to article_path
  end

  def new
    if current_user.role == 'Usuario'
      redirect_to articles_path, alert: 'No tienes permisos para crear nuevos artículos.'
    else
      @article = Article.new
      @categories = Category.all
    end
  end

  def create
    @article = current_user.articles.create(article_params)
    @article.save_categories
    redirect_to @article
  end

  def destroy
    unless @article.user == current_user || current_user.admin?
      redirect_to articles_path, alert: 'No tienes permiso para editar este artículo.'
      return
    end
    @article.remove_category_association
    @article.destroy
    redirect_to root_path
  end

  def from_author
    @user = User.find(params[:user_id])
  end

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, category_elements: [])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="card padding margin-top" >
    <h3 class="text-uppercase"><%= article.title %></h3>
    <p class="text-secondary"><%= article.created_at %></p>
    <%= link_to "Ver más", article %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form|%>

<div class="field">
    <%=form.label :title %>
    <%=form.text_field :title %>
</div>

<div>
    <%=form.label :category_elements %>
    <div class="row">
        <% @categories.each do |category|%>
            <label class="col-6 col-sm-4">
                <%= form.check_box :category_elements, {multiple: true}, category.id, nil%>
                <%= category.title %>
            </label>
        <%end%>
    </div>

</div>

<div class="field">
    <%=form.label :content %>
    <%=form.rich_text_area :content %>
</div>

<div>
    <%=form.submit %>
</div>

<%end%>

app/views/articles/edit.html.erb
<div class="small-container center-block">
    <%= render 'articles/form' %>
</div>

app/views/articles/from_author.html.erb
<div class="large-container center-block">
    <h1>Articulos publicados por <%= @user.email %></h1>

    <%= render @user.articles %>
</div>

app/views/articles/index.html.erb
<div class="large-container center-block">
    <h1>Articulos</h1>

    <%= render @articles %>
</div>

app/views/articles/new.html.erb
<div class="small-container center-block">
    <%= render 'articles/form' %>
</div>

app/views/articles/show.html.erb
<div class="large-container center-block">
    <h1><%= @article.title %></h1>

    <div>
        <p>Escrito por: <strong><%= @article.user.name %></strong> </p>
    </div>

    <div class="margin-top">
        <p class="label">Tags</p>

        <% @article.categories.each do |category| %>
            <span class="badge badge-pill padding" style="background-color:<%= category.color %>">
                <%= link_to category.title, category, class: "text-white" %>
            </span>
        <% end %>

    </div>

    <div>
        <%= @article.content %>
    </div>


    <% if current_user==nil || current_user.role != 'Usuario'%>
        <div>
            <%= link_to "EDITAR", edit_article_path, class: "link" %>
            <%= link_to "ELIMINAR ARTICULO", @article, method: :delete %>
        </div>
    <% end %>

    <div>
        <h2>Agregar Comentario</h2>
        <div class="comment">
            <%= form_with(model: [ @article, Comment.new ], local: true) do |form| %>
                <%= form.text_area :text, placeholder: 'Escribe tu comentario' , cols: 120%>
                <%= form.submit 'Enviar comentario' %>
            <% end %>
        </div>
    </div>

    <div>
        <h2>Comentarios</h2>
        <% @article.comments.each do |comment| %>
        <div class = "comment">
            <% if comment.user.avatar.present? %>
                <%= image_tag comment.user.avatar.variant(resize: '50x50^', crop: '50x50+0+0'), width: 50, height: 50 %>
            <% end %>
            <p>Publicado por: <%= comment.user.name %></p>

            <div class= "comment_content"><p><%= comment.text %></p></div>
            <p>Publicado: <%= comment.created_at.strftime("%d/%m/%Y") %></p>
            <% if current_user.present? %>
                <% if current_user == comment.user || current_user.role == 'Admin'%>
                    <%= button_to "Eliminar comentario", article_comment_path(@article, comment), method: :delete, data: { confirm: "¿Estás seguro de eliminar este comentario?" } %>
                <% end %>
            <% end %>
        </div>
        <% end %>
    </div>
</div>