config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { registrations: 'users/registrations', sessions: 'users/sessions',
                            passwords: 'users/passwords' }
  # devise_for :users

  # devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/bienvenida', to: 'home#index'

  resources :users do
    get 'my_comments', on: :member
    get 'my_articles', on: :member
  end

  resources :users, only: [:update]
  get 'perfil', to: 'users#edit'
  delete '/users/:id', to: 'users#destroy', as: :delete_user

  # get '/users/:id', to: 'users#show', as: 'user_profile'

  root to: 'home#index'

  resources :categories
  resources :articles do
    get 'user/:user_id', to: 'articles#from_author', on: :collection
    resources :comments, only: %i[create destroy]
  end

  # resources :articles do
  #   resources :comments, only: [:create, :destroy]
  # end

  # get "articles", to:"articles#index"
  # get "articles/new", to: "articles#new", as: :new_articles
  # get "articles/:id", to: "articles#show"
  # get "articles/:id/edit", to: "articles#edit"
  # patch "/articles/:id", to: "articles#update", as: :article
  # post "articles", to: "articles#create"
  # delete "articles/:id", to: "articles#destroy"
end

app/views/partials/_nav.html.erb
<nav class="nav bg-light padding navbar">
  <div class="navbar-left">
    <ul class="nav">
      <li class="nav-item">
        <%= link_to "Inicio", root_path, class: "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Artículos", articles_path, class: "nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Categorias", categories_path, class: "nav-link" %>
      </li>

      <% if user_signed_in? && current_user.role != 'Usuario' %>
        <!-- Opción de la navbar que deseas ocultar -->
        <li class="nav-item">
          <%= link_to "Nuevo Artículo", new_article_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="navbar-right">
    <ul class="nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Perfil", perfil_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <p class="nav-link"><%= current_user.email%></p>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Iniciar sesión", new_user_session_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Registro", new_user_registration_path, class: "nav-link"%>
        </li>
      <% end %>
    </ul>
  </div>
</nav>